volumes:
  static:

services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: django
    env_file:
      - docker/env/.env.dev
    volumes:
      - ./:/app
      - static:/app/static
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/app/static
      - ./docker/nginx/dev/django.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django